name: Daily Horoscope

on:
  schedule:
    # Запускать каждый день в 08:00 по UTC (07:00 по Киеву в зимнее время, 09:00 в летнее)
    # Время может быть изменено на ваше усмотрение
    - cron: '0 8 * * *'
  workflow_dispatch: # Позволяет запускать вручную из интерфейса GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # Шаг для получения кода из репозитория
      with:
        fetch-depth: 0 # Для получения полной истории, если нужно

    - name: Set up Python # Шаг для настройки Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Используйте последнюю версию Python 3

    - name: Install dependencies # НОВЫЙ ШАГ: Установка Python-зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install requests google-generativeai

    - name: Run bot script # Шаг для запуска вашего бота
      run: python bot_script.py
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
