name: Daily Horoscope

on:
  schedule:
    - cron: '0 6 * * *'  # каждый день в 09:00 по Киеву (UTC+3 = 6:00 UTC)
  workflow_dispatch:

jobs:
  send_horoscope:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install openai python-telegram-bot==13.15

      -       - name: Run bot script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
        run: python bot_script.py